### ISSUE TITLE
Make menus more readable

### ISSUE THREAD

**Issue by fasttransients** [sokirill/logseq-panic-theme#2]
First off—I love this theme. Thank you so much for it! I wouldn't have thought that "something like this" would become my daily driver, but there you go.

Only the menus could be a bit more "readable", as in:

1. have a border, a drop shadow, or a darker or lighter background color so they're easily distinguishable from what's underneath
2. have the same bright text color on mouse hover as when selected using the keyboard

Thank you so much again!

<img width="374" alt="Screen Shot 2021-12-22 at 12 26 38" src="https://user-images.githubusercontent.com/93603146/147085899-d3332f26-6d09-4d62-b265-5465623253c0.png">

<img width="504" alt="Screen Shot 2021-12-22 at 12 28 00" src="https://user-images.githubusercontent.com/93603146/147086021-0e4fd107-ba25-4de8-987a-5d759c630d4e.png">

**Comment by sokirill** [comment]
Brilliant suggestion! This theme is still work in progress so thank you for coming up with improvements. I will submit an update by end January, just got caught in the holiday season.

**Comment by sokirill** [comment]
Made a quick fix to the menu color for now. It is a bit hard to target it because it influences other elements and there is no menu class or selector as of now. Will keep this in mind and will try to rework in the future. Also see the discussion here: https://discord.com/channels/725182569297215569/752845138148982877/927081452993146882

**Comment by fasttransients** [comment]
Thanks for the follow-up!

**Comment by fasttransients** [comment]
As a quick fix for the time being I updated my css with:

```css
.ui__modal-panel,
.absolute-modal,
.rounded-md {
	border-radius: 0;
}

.dropdown-wrapper,
.ui__modal-panel,
.absolute-modal,
.modal {
	border: 1px solid var(--ls-border-color);
}

.menu-link:hover {
	color: var(--ls-primary-text-color);
}
```

So that all menus have a border, and mouse hover colors work as intended.
