### ISSUE TITLE
FR: increase legibility of hovered links

### ISSUE THREAD

**Issue by fasttransients** [sokirill/logseq-panic-theme#5]
(Most of the) links are pretty hard to read on hover.

Something like this would increase legibility:

```css
.timestamp-label+a:hover,
.marker-switch:hover,
.external-link:hover,
.block-ref:hover,
.page-ref:hover {
	color: var(--white-hover);
}
```
